// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pubservice.proto

package pubservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type String struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *String) Reset() {
	*x = String{}
	mi := &file_pubservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_pubservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_pubservice_proto_rawDescGZIP(), []int{0}
}

func (x *String) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pubservice_proto protoreflect.FileDescriptor

const file_pubservice_proto_rawDesc = "" +
	"\n" +
	"\x10pubservice.proto\x12\n" +
	"pubservice\"4\n" +
	"\x06String\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\xb5\x01\n" +
	"\rPubsubService\x121\n" +
	"\aPublish\x12\x12.pubservice.String\x1a\x12.pubservice.String\x12:\n" +
	"\x0eSubscribeTopic\x12\x12.pubservice.String\x1a\x12.pubservice.String0\x01\x125\n" +
	"\tSubscribe\x12\x12.pubservice.String\x1a\x12.pubservice.String0\x01B2Z0http://github.com/spr-networks/sprbus/pubserviceb\x06proto3"

var (
	file_pubservice_proto_rawDescOnce sync.Once
	file_pubservice_proto_rawDescData []byte
)

func file_pubservice_proto_rawDescGZIP() []byte {
	file_pubservice_proto_rawDescOnce.Do(func() {
		file_pubservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pubservice_proto_rawDesc), len(file_pubservice_proto_rawDesc)))
	})
	return file_pubservice_proto_rawDescData
}

var file_pubservice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pubservice_proto_goTypes = []any{
	(*String)(nil), // 0: pubservice.String
}
var file_pubservice_proto_depIdxs = []int32{
	0, // 0: pubservice.PubsubService.Publish:input_type -> pubservice.String
	0, // 1: pubservice.PubsubService.SubscribeTopic:input_type -> pubservice.String
	0, // 2: pubservice.PubsubService.Subscribe:input_type -> pubservice.String
	0, // 3: pubservice.PubsubService.Publish:output_type -> pubservice.String
	0, // 4: pubservice.PubsubService.SubscribeTopic:output_type -> pubservice.String
	0, // 5: pubservice.PubsubService.Subscribe:output_type -> pubservice.String
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pubservice_proto_init() }
func file_pubservice_proto_init() {
	if File_pubservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pubservice_proto_rawDesc), len(file_pubservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pubservice_proto_goTypes,
		DependencyIndexes: file_pubservice_proto_depIdxs,
		MessageInfos:      file_pubservice_proto_msgTypes,
	}.Build()
	File_pubservice_proto = out.File
	file_pubservice_proto_goTypes = nil
	file_pubservice_proto_depIdxs = nil
}
